const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const tabs=$$('#tabs [role="tab"]');const panels=$$('.panel');const menu=$('.menu-toggle');
function activate(id){tabs.forEach(t=>{const on=t.dataset.tab===id;t.setAttribute('aria-selected',on);});panels.forEach(p=>{const on=p.id===`panel-${id}`;p.hidden=!on;p.classList.toggle('active',on);});localStorage.setItem('peligro-tab',id);if(innerWidth<761)$('#tabs').classList.remove('open');}
tabs.forEach(t=>t.addEventListener('click',()=>activate(t.dataset.tab)));menu.addEventListener('click',()=>{const open=$('#tabs').classList.toggle('open');menu.setAttribute('aria-expanded',open)});activate(localStorage.getItem('peligro-tab')||'huella');
const footprint=['Uso el mismo alias en varias redes','Mi email aparece en perfiles públicos','Tengo repositorios con commits antiguos','He subido fotos con ubicaciones reconocibles','Uso apps con permisos de ubicación permanentes','Hay PDFs míos publicados con metadatos','No reviso filtraciones de contraseña','Tengo cuentas viejas sin borrar'];
$('#footprint-checks').innerHTML=footprint.map((x,i)=>`<label><input type="checkbox" value="${i}"> ${x}</label>`).join('');
function updateFoot(){const n=$$('#footprint-checks input:checked').length;const pct=Math.round(n/footprint.length*100);$('#footprint-bar').style.width=pct+'%';const msg=pct<25?'Exposición baja: sigues siendo humano, pero con cortinas.':pct<55?'Exposición media: toca limpiar alias, permisos y cuentas zombie.':'Exposición alta: tu yo digital deja más migas que Hansel con fibra.';$('#footprint-result').textContent=`${pct}% · ${msg}`;}$('#footprint-checks').addEventListener('change',updateFoot);updateFoot();
const lex={miedo:['amenaza','peligro','caos','colapso','invasión','ruina','desastre'],urgencia:['ahora','inmediato','última oportunidad','antes de que','urgente'],autoridad:['expertos','oficial','científico','según fuentes','incuestionable'],tribu:['ellos','nosotros','enemigo','traidores','la gente de bien']};
$('[data-action="analyze-bias"]').onclick=()=>{const text=$('#bias-input').value.toLowerCase();let rows=[];for(const [k,words] of Object.entries(lex)){const hits=words.filter(w=>text.includes(w));rows.push(`${k.toUpperCase()}: ${hits.length?hits.join(', '):'sin señales claras'}`)}$('#bias-output').textContent=rows.join('\n')+'\n\nPregunta útil: ¿qué emoción intenta activar antes de darte pruebas?';};
const thinkerData={Orwell:'vigilar el lenguaje es vigilar lo pensable; si aceptas palabras prefabricadas, aceptas jaulas prefabricadas.', 'Hannah Arendt':'el peligro empieza cuando la obediencia burocrática sustituye al juicio personal.', Maquiavelo:'el poder no se juzga solo por sus discursos, sino por los mecanismos con los que conserva estabilidad.', 'Mary Wollstonecraft':'sin educación crítica, la libertad es decoración bonita sobre dependencia real.', Nietzsche:'pregunta siempre qué voluntad se esconde detrás de una moral aparentemente pura.', 'Simone Weil':'la atención es una forma de justicia; la propaganda triunfa cuando roba la atención.'};
$('[data-action="debate"]').onclick=()=>{const t=$('#thinker').value,topic=$('#debate-topic').value||'el poder';$('#debate-output').textContent=`${t} ante "${topic}":\nTesis: ${thinkerData[t]}\nObjeción honesta: una idea brillante también puede convertirse en dogma si se usa como martillo universal.\nPregunta incómoda: ¿quién gana si dejas de hacer esta pregunta?`;};
$('[data-action="crisis"]').onclick=()=>{const c=$('#crisis-kind').value,p=$('#crisis-priority').value;const scores={ 'verificar información':92,'coordinar vecinos':88,'proteger suministros':74,'reducir exposición digital':81};$('#crisis-output').textContent=`Crisis: ${c}.\nDecisión inicial: ${p}.\nÍndice de supervivencia cívica: ${scores[p]}/100.\nConsecuencia: reduces ruido, evitas pánico y conviertes el grupo de WhatsApp en algo apenas menos infernal. Siguiente paso: documentar fuentes y acordar canales de confianza.`;};
$('[data-action="phish"]').onclick=()=>{const text=$('#phish-input').value.toLowerCase();const checks=[['urgencia',/urgente|24 horas|inmediato|bloquead/],['premio o amenaza',/premio|suspendida|multa|ganador|verifica/],['enlace sospechoso',/http|\.zip|bit\.ly|login|secure/],['petición de secreto',/contraseña|tarjeta|código|pin|dni/]];const hits=checks.filter(([,re])=>re.test(text)).map(([n])=>n);$('#phish-output').textContent=hits.length?`Señales encontradas: ${hits.join(', ')}.\nAcción segura: no pulses; entra manualmente en la web oficial y consulta desde allí.`:'No veo señales típicas, pero eso no lo convierte en santo. Verifica remitente, dominio y contexto.';};
$('[data-action="news"]').onclick=()=>{const base=$('#news-input').value.trim()||'Se anuncia una medida pública.';const tone=$('#news-tone').value;const frames={alarmista:`ALERTA: ${base} Expertos vecinales advierten de una transformación silenciosa que podría afectar a miles de ciudadanos antes de que nadie pueda reaccionar.`,institucional:`${base} La medida se presenta como una actualización orientada a mejorar la gestión pública, con revisión técnica y comunicación progresiva.`,populista:`${base} Otra decisión tomada desde arriba mientras la gente normal se entera cuando ya está todo firmado.`,tecnocrático:`${base} El proyecto optimiza flujos urbanos mediante métricas agregadas, gobernanza de datos y eficiencia operacional.`, 'conspirativo teatral':`${base} Casualidad, por supuesto. Como siempre que una infraestructura de control aparece justo cuando nadie mira el anexo técnico.`};$('#news-output').textContent=frames[tone]+`\n\nTruco usado: encuadre ${tone}. Ahora separa datos, interpretación y emoción.`;};
let watch=[];$('[data-action="watch"]').onclick=()=>{const place=$('#watch-place').value.trim()||'punto sin nombre',type=$('#watch-type').value;watch.push({place,type});$('#watch-output').innerHTML=watch.map((x,i)=>`${i+1}. ${x.place} · ${x.type}`).join('\n')+'\n\nLectura: identifica responsable, finalidad, retención y alternativa sin seguimiento.';};
const puzzles=[{q:'"Todos dicen lo mismo con palabras distintas y publican cada 90 segundos."',a:'bot',h:'Cadencia y repetición.'},{q:'"Como ciudadano preocupado, te pido compartir esto antes de que lo censuren."',a:'propaganda',h:'Urgencia + persecución.'},{q:'"No estoy seguro; puedo estar equivocado, pero estos son mis motivos."',a:'humano',h:'Incertidumbre razonada.'},{q:'"La fuente es incuestionable porque lo afirma la propia fuente."',a:'propaganda',h:'Autoridad circular.'},{q:'"He leído el documento y la página 14 contradice el titular."',a:'humano',h:'Referencia verificable.'}];let idx=0,score=0;function renderEscape(){const p=puzzles[idx%puzzles.length];$('#escape-card').textContent=`Caso ${idx+1}: ${p.q}`;$('#escape-score').textContent=`Puntuación: ${score}/${idx}`;}renderEscape();$$('[data-answer]').forEach(b=>b.onclick=()=>{const p=puzzles[idx%puzzles.length];const ok=b.dataset.answer===p.a;score+=ok?1:0;idx++;$('#escape-card').textContent=(ok?'Correcto. ':'No exactamente. ')+`Pista: ${p.h}`;setTimeout(renderEscape,900);});
